$(document).ready(function(){
    $("#js-navigation-button").click(function(){
        $("#js-navigation").slideToggle();
    });
    $("#button").click(function(){
        $(".js-display").slideToggle("slow");
    });
    $("#button1").click(function(){
        $(".js-display1").slideToggle("slow");
    });
    $("#button2").click(function(){
        $(".js-display2").slideToggle("slow");
    });
    $("#button3").click(function(){
        $(".js-display3").slideToggle("slow");
    });
    $("#button4").click(function(){
        $(".js-display4").slideToggle("slow");
    });
    $("#button5").click(function(){
        $(".js-display5").slideToggle("slow");
    });
    $("#button6").click(function(){
        $(".js-display6").slideToggle("slow");
    });
    $("#button7").click(function(){
        $(".js-display7").slideToggle("slow");
    });
    $("#button8").click(function(){
        $(".js-display8").slideToggle("slow");
    });
    $("#button9").click(function(){
        $(".js-display9").slideToggle("slow");
    });
    $("#button10").click(function(){
        $(".js-display10").slideToggle("slow");
    });
    $("#button11").click(function(){
        $(".js-display11").slideToggle("slow");
    });

});
// optional
$('#blogCarousel').carousel({
    interval: 5000
});
